"""add_efficiency_score_delay_to_tasks

Revision ID: 26b071487482
Revises: ec9ffaf72d20
Create Date: 2026-05-18 16:30:31.868198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26b071487482'
down_revision: Union[str, Sequence[str], None] = 'ec9ffaf72d20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('delay_minutes', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('efficiency_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'efficiency_score')
    op.drop_column('tasks', 'delay_minutes')
    # ### end Alembic commands ###
