"""upgrade tasks to enterprise

Revision ID: 5d75254299c2
Revises: a824f2fdeb18
Create Date: 2026-05-18 14:27:41.635803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5d75254299c2'
down_revision: Union[str, Sequence[str], None] = 'a824f2fdeb18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Create PostgreSQL enum types before they are referenced
    taskpriority_enum = postgresql.ENUM('critical', 'high', 'normal', 'low', name='taskpriority')
    taskstatus_enum = postgresql.ENUM('new', 'assigned', 'in_progress', 'pending_review', 'approved', 'rejected', name='taskstatus')
    taskpriority_enum.create(op.get_bind(), checkfirst=True)
    taskstatus_enum.create(op.get_bind(), checkfirst=True)

    # Add non-nullable columns with a temporary server_default for existing rows
    op.add_column('tasks', sa.Column('priority', sa.Enum('critical', 'high', 'normal', 'low', name='taskpriority', create_type=False), nullable=False, server_default='normal'))
    op.add_column('tasks', sa.Column('due_date', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')))
    op.add_column('tasks', sa.Column('approved_by', sa.UUID(), nullable=True))
    op.add_column('tasks', sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('rejection_reason', sa.Text(), nullable=True))
    op.add_column('tasks', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))

    # Remove temporary server defaults — values are now set, columns remain NOT NULL
    op.alter_column('tasks', 'priority', server_default=None)
    op.alter_column('tasks', 'due_date', server_default=None)

    op.alter_column('tasks', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('tasks', 'assigned_to',
               existing_type=sa.UUID(),
               nullable=True)

    # Normalize any legacy status values before casting to enum
    op.execute("UPDATE tasks SET status = 'new' WHERE status NOT IN ('new', 'assigned', 'in_progress', 'pending_review', 'approved', 'rejected')")
    op.alter_column('tasks', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('new', 'assigned', 'in_progress', 'pending_review', 'approved', 'rejected', name='taskstatus', create_type=False),
               existing_nullable=False,
               postgresql_using='status::taskstatus')

    op.create_foreign_key(None, 'tasks', 'users', ['approved_by'], ['id'])
    op.drop_column('tasks', 'latitude')
    op.drop_column('tasks', 'longitude')
    op.drop_column('tasks', 'started_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.alter_column('tasks', 'status',
               existing_type=sa.Enum('new', 'assigned', 'in_progress', 'pending_review', 'approved', 'rejected', name='taskstatus'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('tasks', 'assigned_to',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('tasks', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('tasks', 'deleted_at')
    op.drop_column('tasks', 'rejection_reason')
    op.drop_column('tasks', 'approved_at')
    op.drop_column('tasks', 'approved_by')
    op.drop_column('tasks', 'due_date')
    op.drop_column('tasks', 'priority')

    # Drop enum types after columns are removed
    postgresql.ENUM(name='taskstatus').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='taskpriority').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
