"""add field tracking to tasks

Revision ID: 8fb1a4e07cba
Revises: 95aa420e4001
Create Date: 2026-05-18 10:34:49.552893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fb1a4e07cba'
down_revision: Union[str, Sequence[str], None] = '95aa420e4001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('tasks', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('tasks', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'completed_at')
    op.drop_column('tasks', 'started_at')
    op.drop_column('tasks', 'longitude')
    op.drop_column('tasks', 'latitude')
    # ### end Alembic commands ###
