"""add created_by to tasks

Revision ID: 95aa420e4001
Revises: 0b43560745f9
Create Date: 2026-05-18 10:27:02.517772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95aa420e4001'
down_revision: Union[str, Sequence[str], None] = '0b43560745f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add nullable first so existing rows don't violate NOT NULL
    op.add_column('tasks', sa.Column('created_by', sa.UUID(), nullable=True))
    # Backfill: treat assigned_to as the creator for all pre-existing rows
    op.execute('UPDATE tasks SET created_by = assigned_to WHERE created_by IS NULL')
    # Now enforce NOT NULL
    op.alter_column('tasks', 'created_by', nullable=False)
    op.create_foreign_key(None, 'tasks', 'users', ['created_by'], ['id'])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'created_by')
    # ### end Alembic commands ###
