"""create_expenses_table

Revision ID: ce40054b0be5
Revises: b8ea91b720ef
Create Date: 2026-05-18 16:21:04.241030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce40054b0be5'
down_revision: Union[str, Sequence[str], None] = 'b8ea91b720ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expenses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('category', sa.Enum('travel', 'meals', 'equipment', 'software', 'accommodation', 'fuel', 'other', name='expensecategory'), nullable=False),
    sa.Column('receipt_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('draft', 'submitted', 'supervisor_approved', 'finance_approved', 'rejected', 'reimbursed', name='expensestatus'), nullable=False),
    sa.Column('submitted_by', sa.UUID(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('supervisor_id', sa.UUID(), nullable=True),
    sa.Column('supervisor_approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finance_id', sa.UUID(), nullable=True),
    sa.Column('finance_approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_by', sa.UUID(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('reimbursed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['finance_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['rejected_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['supervisor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expenses')
    # ### end Alembic commands ###
